// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using MyBackend.Data;

#nullable disable

namespace backendLearning.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")  // Make sure the version matches your EF Core version
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // Remove SQL Server-specific configuration (like UseIdentityColumns) for SQLite

            modelBuilder.Entity("MyBackend.Data.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");  // SQLite uses INTEGER for auto-incrementing primary keys

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("TEXT");  // SQLite uses TEXT for strings

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("TEXT");  // SQLite uses TEXT for strings

                b.HasKey("Id");

                b.ToTable("Users");
            });
        }
    }
}
